apiVersion: v2
appVersion: 2.1.7
dependencies:
- condition: redis-cluster.enabled
  name: redis-cluster
  repository: https://charts.bitnami.com/bitnami
  version: 11.5.3
description: A Helm chart for Kubernetes
name: security-engine
type: application
version: 2.1.7
