{{- range $streamName:=.Values.streams }}
{{- with $ -}}
{{- $serviceSuffix := "" }}
  {{- if ne $streamName "general" }}
    {{- $serviceSuffix = printf "-%s" $streamName }}
  {{- end }}

apiVersion: v1
kind: Service
metadata:
  name: {{ template "normalizer.fullname" . }}{{$serviceSuffix}}
  labels:
    app: {{ template "normalizer.name" . }}
    chart: {{ template "normalizer.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
{{ toYaml .Values.service.labels | indent 4 }}
  annotations:
{{ toYaml .Values.service.annotations | indent 4 }}

spec:
  type: {{ .Values.service.type }}
  ports:
{{ toYaml .Values.service.ports | indent 2 }}
  selector:
    app: {{ template "normalizer.name" . }}{{$serviceSuffix}}
    release: {{ .Release.Name }}
{{- end }}
---
{{- end }}