{{- if eq "envoy" .Values.global.ingressType }}
apiVersion: v1
kind: Service
metadata:
  name: imperva-envoy
  # name: {{ include "envoy.fullname" . }}
  labels: 
    {{- include "envoy.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "envoy.selectorLabels" . | nindent 4 }}
{{- end }}
