standalone: "true"
fullnameOverride: "apisec-controller-message-bus"

securityContext:
  readOnlyRootFilesystem: false

image:
  registry: imperva.jfrog.io/apisec-airgap-stage
  repository: apisec-controller-message-bus
  tag: 0.0.1-main.19-7f5100
  pullPolicy: IfNotPresent

imagePullSecrets:
  - name: apisecurity-credentials

env:
  DEPLOYMENT_PROFILE: "ON-PREM"

volumes:
  - name: tmp
    emptyDir: {}

volumeMounts:
  - mountPath: /tmp
    name: tmp

resources:
  requests:
    memory: "2560Mi"
    cpu: "500m"
  limits:
    memory: "3384Mi"
    cpu: "1000m"
