global:
  env: prod
  debug: false
  ingressControllerNamespace: gloo-system # Namespace where the Kong Gateway deployment is installed
  failOpen: false # value which enables the traffic if LSE pod is unavailable (default is false, no traffic allowed)
  registry: imperva.jfrog.io # Registry for the images, will be used throughout the charts
  certificates:
    allowAnyCertificate: false # Allow any certificate to be used for the communication with the WAF Anywhere Cloud services
    certFilePath: "" # Path to the certificate file that will be used for the communication with the WAF Anywhere Cloud services. Leave empty to use the default certificates.
    secretCertName: "" # The name of the secret containing the certificate file, supplied by the customer. Must exist in the installation namespace before installation. Leave blank to use the default certificates.
  proxy:
    # Configuration for setting http_proxy, https_proxy, and no_proxy environment variables
    https: "" # Set the proxy that will be used to access URLs that use the HTTP protocol. Leave empty if not needed.
    noProxy: "" # Set a comma-separated list of addresses to exclude from the proxy. Leave empty if not needed.
  autoInstall:
    restartIngressControllerDeployment: false # Restarting the IC deployment, useful for making sure projected volumes on the pod are up-to-date
    autoPatchIngressControllerResources: true # Automatically patch the IC required resources (Deployment)
securityEngineServiceName: imperva-security-engine-svc
securityEngineServicePort: 443
settingsResourceName: default