{{- if .Values.vaultStaticSecrets.enabled }}
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  labels:
    app: {{ template "normalizer.name" . }}
    chart: {{ template "normalizer.chart" . }}
    release: {{ .Release.Name }}
  name: {{ .Values.vaultStaticSecrets.AuthCode.name }}
spec:
  vaultAuthRef: {{ .Values.vaultStaticSecrets.vaultAuthRef }}
  mount: {{ .Values.vaultStaticSecrets.mount }}
  path: {{ .Values.vaultStaticSecrets.AuthCode.path }}
  {{ if .Values.vaultStaticSecrets.AuthCode.version }}
  version: {{ .Values.vaultStaticSecrets.AuthCode.version }}
  {{ end }}
  type: kv-v2
  refreshAfter: {{ .Values.vaultStaticSecrets.refreshAfter }}
  destination:
    name: {{ .Values.vaultStaticSecrets.AuthCode.kubernetesSecretName }}
    create: true
    type: Opaque
  rolloutRestartTargets:
  - kind: Deployment
    name: api-security-engine-normalizer
{{- end }}