{{- $secret_name := printf "%s-%s" (include "bola-detection-engine.name" . ) "certificate-password-secret" }}
{{- $secret_name_pci := printf "%s-%s" (include "bola-detection-engine.name" . ) "pci-certificate-password-secret" }}
{{- if .Values.certManager.enabled }}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ $secret_name }}
data:
  {{- $old_secret := lookup "v1" "Secret" .Release.Namespace $secret_name }}
  {{- if or (not $old_secret) (not $old_secret.data) }}
  password: {{ randAlphaNum 20 | b64enc }}
  {{- else }}
  password:  {{ index $old_secret.data "password" }}
  {{ end }}
{{- end }}
---
{{- if .Values.certManagerPCI.enabled }}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ $secret_name_pci }}
data:
  {{- $old_secret := lookup "v1" "Secret" .Release.Namespace $secret_name }}
  {{- if or (not $old_secret) (not $old_secret.data) }}
  password: {{ randAlphaNum 20 | b64enc }}
  {{- else }}
  password:  {{ index $old_secret.data "password" }}
  {{ end }}
{{- end }}