standalone: "true"

image:
  registry: imperva.jfrog.io/apisec-airgap-stage
  repository: bola-feature-extractor
  tag: 0.0.1-master.153-a19ef3
  pullPolicy: IfNotPresent

imagePullSecrets:
  - name: apisecurity-credentials

env:
  DEPLOYMENT_PROFILE: "ON-PREM"
  PROCESS_PATH_PARAM: "true"
  REDIS_SERVER_ADDR: '{"host":"apisec-controller-message-bus", "port":6379, "cred_source": "env", "is_tls_enabled": false}'
  REDIS_SERVER_CACHE_ADDR: '{"host":"apisec-controller-message-bus", "port":6379, "cred_source": "env", "is_tls_enabled": false}'
  PROMETHEUS_MULTIPROC_DIR: "/tmp/MULTIPROC_DIR_REPORTS"

initContainerEnv:
  REDIS_PROPS: '[{"host":"apisec-controller-message-bus", "port":6379, "cred_source": "env", "is_tls_enabled":false}]'

volumes:
  - name: tmp
    emptyDir: {}

volumeMounts:
  - mountPath: /tmp
    name: tmp

certManager:
  enabled: false

vaultPKISecret:
  enabled: false

resources:
  requests:
    memory: "512Mi"
    cpu: "500m"
  limits:
    memory: "1024Mi"
    cpu: "1000m"
