{{- if eq "envoy-gateway" .Values.global.ingressType -}}
{{- include "envoy-gateway.validations" . }}
apiVersion: gateway.networking.k8s.io/v1alpha3
kind: BackendTLSPolicy
metadata:
  name: {{ $.Values.securityEngineServiceName }}-tls-policy
  namespace: {{ .Release.Namespace }}
spec:
  targetRefs:
  - group: ''
    kind: Service
    name: {{ $.Values.securityEngineServiceName }}
    sectionName: "https"
  validation:
    caCertificateRefs:
    - name: "{{ include "anywhere-commons.get-security-engine-tls-secret-name" .}}"
      group: ''
      kind: Secret
    hostname: {{ $.Values.securityEngineServiceName }}.{{.Release.Namespace}}.svc.cluster.local
{{- end }}