{{- if eq "envoy-gateway" .Values.global.ingressType -}}
{{- include "envoy-gateway.validations" . }}
{{- $httpRoutesByNamespace := include "envoy-gateway.httpRoutesByNamespace" . | fromYaml }}
{{- range $namespace, $routes := $httpRoutesByNamespace }}
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: EnvoyExtensionPolicy
metadata:
    name: imperva-security-engine-ext-proc-{{ $namespace }}
    namespace: {{ $namespace }}
spec:
  targetRefs:
  {{- range $routeName := $routes }}
  - group: gateway.networking.k8s.io
    kind: HTTPRoute
    name: {{ $routeName }}
  {{- end }}
  extProc:
  - backendRefs:
    - name: {{ $.Values.securityEngineServiceName }}
      port: {{ $.Values.securityEngineServicePort }}
      namespace: {{ $.Release.Namespace }}
    processingMode:
      request: 
        body: Streamed
      response: {}
    failOpen: {{ $.Values.global.failOpen }}
---
{{- end }}
{{- end }}