{{- if .Values.autoscaling.enabled }}
{{- range $stream:=.Values.streams }}
{{- with $ -}}
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: {{ template "receiver.fullname" . }}-{{$stream}}
  labels:
    app: {{ template "receiver.name" . }}-{{$stream}}
    chart: {{ template "receiver.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ template "receiver.fullname" . }}-{{$stream}}
{{- if (index .Values.autoscaling $stream) }}
{{ (unset (get .Values.autoscaling $stream) "enabled") | toYaml | indent 2 }}
{{- else }}
{{ (unset (get .Values.autoscaling "general") "enabled") | toYaml | indent 2 }}
{{- end }}
{{- end }}
---
{{- end }}
{{- end }}