{{/* Reference: https://developer.hashicorp.com/vault/docs/platform/k8s/vso/api-reference#vaultpkisecret */}}
{{- if .Values.vaultPKISecret.enabled }}
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultPKISecret
metadata:
  labels:
    app: {{ template "receiver.name" . }}
    chart: {{ template "receiver.chart" . }}
    release: {{ .Release.Name }}
  name: {{ template "receiver.name" . }}-server-certificate
spec:
  vaultAuthRef: {{ .Values.vaultPKISecret.vaultAuthRef }}
  mount: {{ .Values.vaultPKISecret.mount }}
  role: {{ .Values.vaultPKISecret.role }}
  clear: true
  expiryOffset: {{ .Values.vaultPKISecret.expiryOffset }}
  commonName: {{ .Values.vaultPKISecret.commonName }}
  {{- if .Values.vaultPKISecret.altNames }}
  altNames:
    {{- range .Values.vaultPKISecret.altNames }}
    - {{ . }}
    {{- end }}
  {{- end }}
  ttl: {{ .Values.vaultPKISecret.ttl }}
  format: {{ .Values.vaultPKISecret.format }}
  destination:
    name: {{ template "receiver.name" . }}-server-certificate-secret
    create: true
    type: kubernetes.io/tls
{{- end }}
