apiVersion: batch/v1
kind: CronJob
metadata:
  name: updatesecrets-job
spec:
  schedule: "0 */1 * * *" 
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: updatesecret
          automountServiceAccountToken: true
          volumes:
          - name: secret-volume
            secret:
              secretName: controller-secret
          containers:
          - name: {{ .Chart.Name }}
            image: "{{.Values.global.imageregistry}}/{{ .Values.global.apisecPublicRepo}}/{{ .Values.CronJob.image }}"
            env:
            - name: API_X_TYPE
              value: controller
            - name: ID
              valueFrom:
                secretKeyRef:
                  name: controller-secret
                  key: controller-id
            - name: TOKEN
              valueFrom:
                secretKeyRef:
                  name: controller-secret
                  key: controller-token
            - name: ACCOUNT_ID
              valueFrom:
                secretKeyRef:
                  name: controller-secret
                  key: account-id
            - name: JFROG_URL
              valueFrom:
                secretKeyRef:
                  name: controller-secret
                  key: access-token-url
          {{ include "apisec-global-env-vars" . | nindent 12 }}
          restartPolicy: "OnFailure"
