apiVersion: v1
kind: Secret
metadata:
  name: controller-secret
type: Opaque
data:
  controller-id: {{ .Values.CONTROLLER_ID | b64enc | quote }}
  account-id: {{ .Values.ACCOUNT_ID | b64enc | quote }}
  controller-token: {{ .Values.CONTROLLER_TOKEN | b64enc | quote }}
  access-token-url: {{ .Values.JFROG_URL | b64enc | quote }}
  # toJson is used to convert the value of external-site-id to a string
  external-site-id: {{ .Values.external_site_id | toJson | b64enc | quote }}
  # Generate new controller instance id only in case of install
  {{- if .Release.IsInstall }}
  controller-instance: {{ randAlphaNum 32 | b64enc | quote }}
  {{ else }}
  controller-instance: {{ index (lookup "v1" "Secret" .Release.Namespace "controller-secret").data "controller-instance" }}
  {{ end }}
  site-id: {{ .Values.SITE_ID | b64enc | quote }}
