{{- $secret_name := printf "%s-%s" (include "receiver.name" . ) "certificate-password-secret" }}
{{- if .Values.certManager.enabled }}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ $secret_name }}
data:
  {{- $old_secret := lookup "v1" "Secret" .Release.Namespace $secret_name }}
  {{- if or (not $old_secret) (not $old_secret.data) }}
  password: {{ randAlphaNum 20 | b64enc }}
  {{- else }}
  password:  {{ index $old_secret.data "password" }}
  {{ end }}
{{- end }}
