{{- if .Values.certManager.enabled }}
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: {{ template "receiver.name" . }}-vault-issuer
spec:
  vault:
    server: {{ .Values.certManager.vault.server }}
    path: {{ .Values.certManager.vault.path }}
    namespace: {{ .Values.certManager.vault.namespace }}
    auth:
      appRole:
        path: {{ .Values.certManager.vault.appRole.path }}
        roleId: {{ .Values.certManager.vault.appRole.roleId }}
        secretRef:
          name: {{ template "receiver.name" $ }}-vault-approle
          key: secretId
{{- end }}
