{{- if .Values.vaultSecret.enabled }}
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  labels:
    app: {{ template "appl-filter.name" . }}
    chart: {{ template "appl-filter.chart" . }}
    release: {{ .Release.Name }}
  name: {{ .Values.vaultSecret.name }}
spec:
  vaultAuthRef: {{ .Values.vaultSecret.vaultAuthRef }}
  mount: {{ .Values.vaultSecret.mount }}
  path: {{ .Values.vaultSecret.path }}
  {{ if .Values.vaultSecret.version }}
  version: {{ .Values.vaultSecret.version }}
  {{ end }}
  type: kv-v2
  refreshAfter: {{ .Values.vaultSecret.refreshAfter }}
  destination:
    name: {{ .Values.vaultSecret.kubernetesSecretName }}
    create: true
    type: Opaque
  rolloutRestartTargets:
  - kind: Deployment
    name: api-security-engine-appl-filter
{{- end }}