# ConfigMap for sharing metadata between parent chart and subchart
apiVersion: v1
kind: ConfigMap
metadata:
  name: shared-config
data:
  chartVersion: {{.Chart.Version}}
  instanceId: {{ (eq "" .Values.auth.instanceName) | ternary (printf "WAF-Anywhere-%s" (randNumeric 5)) .Values.auth.instanceName }}
  ingressType: {{ .Values.global.ingressType }}
  {{- if regexMatch "^[a-z0-9-]{4,36}$" .Values.auth.controllerPackageKey  }}
  controllerPackageKey: {{ .Values.auth.controllerPackageKey }}
  {{- else }}
  {{ fail ".Values.auth.controllerPackageKey must be supplied and must be betweeen 4 and 36 characters long consist of lower case alphanumeric characters or '-' "}}
  {{end}}
