{{- if and (eq "nginx" .Values.global.ingressType) (include "ingress-controller-ops.createAutoPatchResources" .) -}}
kind: ConfigMap
metadata:
  name: ingress-nginx-patch
  namespace: {{ include "ingressController.namespace" . }}
  annotations:
    "helm.sh/hook": post-install, post-upgrade
    "helm.sh/hook-delete-policy": hook-succeeded, hook-failed, before-hook-creation
    "helm.sh/hook-weight": "-5"
apiVersion: v1
data:
  deploy-patch.json: |
{{ include "nginx.pluginInjection" . | indent 4 }}
  config-patch.json: |
{{ include "nginx.configInjection" . | indent 4 }}
---
kind: ConfigMap
metadata:
  name: ingress-nginx-counter-patch
  namespace: {{ include "ingressController.namespace" . }}
  annotations:
    "helm.sh/hook": pre-delete
    "helm.sh/hook-delete-policy": hook-succeeded, hook-failed, before-hook-creation
    "helm.sh/hook-weight": "-5" # Must be created before the cleanup job
apiVersion: v1
data:
  deploy-patch.json: |
{{ include "nginx.counterPatch" . | indent 4 }}
{{- end -}}