{{/* Reference: https://developer.hashicorp.com/vault/docs/platform/k8s/vso/api-reference#vaultpkisecret */}}
{{- if .Values.vaultPKISecret.enabled }}
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultPKISecret
metadata:
  labels:
    app: {{ template "summarization-engine.name" . }}
    chart: {{ template "summarization-engine.chart" . }}
    release: {{ .Release.Name }}
  name: {{ template "summarization-engine.name" . }}-certificate
spec:
  vaultAuthRef: {{ .Values.vaultPKISecret.vaultAuthRef }}
  mount: {{ .Values.vaultPKISecret.mount }}
  role: {{ .Values.vaultPKISecret.role }}
  revoke: {{ .Values.vaultPKISecret.revoke }}
  clear: true
  expiryOffset: {{ .Values.vaultPKISecret.expiryOffset }}
  commonName: {{ .Values.vaultPKISecret.commonName }}
  ttl: {{ .Values.vaultPKISecret.ttl }}
  format: {{ .Values.vaultPKISecret.format }}
  privateKeyFormat: {{ .Values.vaultPKISecret.privateKeyFormat }}
  destination:
    name: {{ template "summarization-engine.name" . }}-certificate-secret
    create: true
    type: kubernetes.io/tls
  rolloutRestartTargets:
  - kind: Deployment
    name: api-security-engine-summarization-engine
{{- end }}
