apiVersion: v1
entries:
  imperva-stack:
  - apiVersion: v2
    appVersion: 2.1.0
    created: "2025-10-12T10:06:08.682205+03:00"
    dependencies:
    - import-values:
      - child: defaults
        parent: global.defaults
      name: anywhere-connectors
      repository: file://charts/anywhere-connectors
      tags:
      - waf
      - waap
      version: 0.7.1
    - name: security-engine
      repository: file://charts/security-engine
      tags:
      - waf
      - waap
      version: 2.1.7
    - name: awf
      repository: file://charts/awf
      tags:
      - waf
      - waap
      version: 1.59.0
    - name: apisecurity
      repository: https://imperva.jfrog.io/artifactory/apisec-falcon-legacy-stage
      tags:
      - waap
      version: '*'
    description: Imperva Anywhere Solution
    digest: 030ee009f811a6b2ac64e0e3b1f4033f7d6da03cf70b31f29335643abfee9547
    name: imperva-stack
    type: application
    urls:
    - https://morbendor.github.io/helm-test/charts/imperva-stack-2.1.0.tgz
    version: 2.1.0
generated: "2025-10-12T10:06:08.667726+03:00"
