apiVersion: v1
entries:
  imperva-stack:
  - apiVersion: v2
    appVersion: 2.1.0
    created: "2025-10-09T15:39:50.555441+03:00"
    dependencies:
    - import-values:
      - child: defaults
        parent: global.defaults
      name: anywhere-connectors
      repository: file://charts/anywhere-connectors
      tags:
      - waf
      - waap
      version: 0.7.1
    - name: security-engine
      repository: file://charts/security-engine
      tags:
      - waf
      - waap
      version: 2.1.7
    - name: awf
      repository: file://charts/awf
      tags:
      - waf
      - waap
      version: 1.59.0
    - name: apisecurity
      repository: https://imperva.jfrog.io/artifactory/apisec-falcon-legacy-stage
      tags:
      - waap
      version: '*'
    description: Imperva Anywhere Solution
    digest: 6c32dd742f087dab5897b1bfbd2c745fd9bfa61a338c9fa6db3ab368a44b67b3
    name: imperva-stack
    type: application
    urls:
    - https://morbendor.github.io/helm-test/charts/imperva-stack-2.1.0.tgz
    version: 2.1.0
generated: "2025-10-09T15:39:50.546205+03:00"
