apiVersion: v1
entries:
  imperva-stack:
  - apiVersion: v2
    appVersion: 2.1.0
    created: "2025-10-15T11:04:08.69371+03:00"
    dependencies:
    - import-values:
      - child: defaults
        parent: global.defaults
      name: anywhere-connectors
      repository: file://charts/anywhere-connectors
      tags:
      - waf
      - waap
      version: 0.7.1
    - name: security-engine
      repository: file://charts/security-engine
      tags:
      - waf
      - waap
      version: 2.1.7
    - name: awf
      repository: file://charts/awf
      tags:
      - waf
      - waap
      version: 1.59.0
    - name: apisecurity
      repository: https://imperva.jfrog.io/artifactory/apisec-falcon-legacy-stage
      tags:
      - waap
      version: '*'
    description: Imperva Anywhere Solution
    digest: 7a325445a7402d82474e10f4e88068bad6becc76e7d2916e39ac07bbd1481cb6
    name: imperva-stack
    type: application
    urls:
    - https://morbendor.github.io/helm-test/charts/imperva-stack-2.1.0.tgz
    version: 2.1.0
generated: "2025-10-15T11:04:08.680265+03:00"
