# WAF Anywhere Secrets for the Ingress Controller namespace
apiVersion: v1
kind: Secret
metadata:
  name: waf-anywhere-artifactory
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "imagePullSecret" . }}
---
{{- if and (include "is-ingress-controller-ns-secret-required" .) (ne .Release.Namespace (include "ingressController.namespace" .)) -}}
# WAF Anywhere Secrets for the image pull secrets on the Ingress Controller namespace
apiVersion: v1
kind: Secret
metadata:
  namespace: {{ include "ingressController.namespace" . }}
  name: waf-anywhere-artifactory
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "imagePullSecret" . }}
{{- end }}