{{- if include "update-image-pull-secrets-job.shouldRun" . }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: update-image-pull-secret-job-role-{{ .Release.Namespace }}
rules:
  - apiGroups:
      - "*"
    resources:
      - secrets
    resourceNames:
      - waf-anywhere-artifactory
    verbs:
      - patch
      - get
      - create
---
# Binding the role to the Anywhere namespace
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: update-image-pull-secret-role-binding-{{ .Release.Namespace }}
  namespace: {{ .Release.Namespace }}
{{- include "update-image-pull-secrets-job.roleBinding" . | nindent 0 }}
---
{{- if (include "is-ingress-controller-ns-secret-required" .)}}
# Binding the role to the ingress controller namespace
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: update-image-pull-secret-role-binding-{{ .Values.global.ingressType }}
  namespace: {{ include "ingressController.namespace" . }}
{{- include "update-image-pull-secrets-job.roleBinding" . | nindent 0 }}
---
{{- end }}
{{- end }}
