apiVersion: v1
kind: Service
metadata:
  name: {{ template "appl-clf-engine.fullname" . }}
  labels:
    app: {{ template "appl-clf-engine.name" . }}
    chart: {{ template "appl-clf-engine.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
{{ toYaml .Values.service.labels | indent 4 }}
  annotations:
{{ toYaml .Values.service.annotations | indent 4 }}

spec:
  type: {{ .Values.service.type }}
  ports:
{{ toYaml .Values.service.ports | indent 2 }}
  selector:
    app: {{ template "appl-clf-engine.name" . }}
    release: {{ .Release.Name }}
