{{- if  .Values.jobs.checkPrerequisites }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: check-prerequisites-role
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "-2"
rules:
  - apiGroups:
      - "apps"
    resources:
      - deployments
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ""
    resources:
      - pods
      - nodes
      - services
      - configmaps
      - version
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - "storage.k8s.io"
    resources:
      - storageclasses
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - "apiextensions.k8s.io"
    resources:
      - customresourcedefinitions
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - "nginx.org"
    resources:
      - globalconfigurations
    verbs:
      - get
      - list
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: check-prerequisites-role-binding
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "-2"
subjects:
  - kind: ServiceAccount
    name: check-prerequisites-hook
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: check-prerequisites-role 
  apiGroup: rbac.authorization.k8s.io
{{- end }}
