{{- $root := . -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-security-engine-bola-detection-engine
  labels:
    app: {{ template "bola-detection-engine.name" . }}
    chart: {{ template "bola-detection-engine.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    tags.datadoghq.com/env: {{ .Release.Namespace }}
    tags.datadoghq.com/service: {{ template "bola-detection-engine.name" . }}
    tags.datadoghq.com/version:  {{ template "bola-detection-engine.version" . }}
spec:
  strategy:
{{ toYaml .Values.updateStrategy | indent 4 }}
  replicas: {{ .Values.replicaCount }}
  minReadySeconds: {{ .Values.minReadySeconds }}
  selector:
    matchLabels:
      app: {{ template "bola-detection-engine.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "bola-detection-engine.name" . }}
        release: {{ .Release.Name }}
      annotations:
{{ toYaml .Values.deployment.annotations | indent 8 }}
    spec:
      {{ if eq (default "" .Values.standalone | toString) "true" }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- end }}

      {{- range $name, $value := .Values.env }}
        {{- if eq "REGION" $name }}
          {{- if contains "eks" $value }}
      serviceAccountName: {{ template "bola-detection-engine.fullname" . }}
      automountServiceAccountToken: true
          {{- end }}
        {{- end }}
      {{- end }}

      {{ if eq (default "" .Values.standalone | toString) "true" }}
      initContainers:
        - name: apisec-infra-utility
          image: {{ template "bola-detection-engine.imageregistry" . }}/{{ .Values.global.InitContainerInfraUtility.image }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- if .Values.initContainerEnv }}
          env:
          {{- range $k, $v := .Values.initContainerEnv }}
            - name: {{ $k }}
              value: {{ $v | quote }}
          {{- end }}
          {{- end }}
      {{- end }}
      restartPolicy: Always
      containers:
        - name: {{ .Chart.Name }}
          image: {{ template "bola-detection-engine.imageregistry" . }}/{{ .Values.image.repository }}:{{ template "bola-detection-engine.imagetag" . }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
{{ toYaml .Values.deployment.ports | indent 10 }}
          {{- if .Values.env }}
          env:
          {{- range $k, $v := .Values.env }}
            - name: {{ $k }}
              value: {{ $v | quote }}
          {{- end }}
          {{- if .Values.certManager.enabled }}
            - name: KEYSTORE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ template "bola-detection-engine.name" . }}-certificate-password-secret
                  key: password
          {{- end }}
          {{- if .Values.certManagerPCI.enabled }}
            - name: KAFKA_SHARED_KEYSTORE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ template "bola-detection-engine.name" . }}-pci-certificate-password-secret
                  key: password
          {{- end }}
          {{ if eq (default "" .Values.standalone | toString) "true" }}
            - name: CONTROLLER_ID
              valueFrom:
                secretKeyRef:
                  name: controller-secret
                  key: controller-id
            - name: CONTROLLER_TOKEN
              valueFrom:
                secretKeyRef:
                  name: controller-secret
                  key:  controller-token
            - name: CONTROLLER_INSTANCE
              valueFrom:
                secretKeyRef:
                  name: controller-secret
                  key: controller-instance
            - name: ACCOUNT_ID
              valueFrom:
                secretKeyRef:
                  name: controller-secret
                  key: account-id
            - name: EXTERNAL_SITE_ID
              valueFrom:
                secretKeyRef:
                  name: controller-secret
                  key: external-site-id
          {{- end }}
            - name: DD_AGENT_HOST
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: DD_ENV
              value: {{ .Release.Namespace }}
            - name: DD_SERVICE
              value: {{ template "bola-detection-engine.name" . }}
            - name: DD_VERSION
              value:  {{ template "bola-detection-engine.version" . }}
            - name: DD_PROFILING_ENABLED
              value: "true"
            - name: DD_LOGS_INJECTION
              value: "true"
            - name: DD_TRACE_SAMPLE_RATE
              value: "1"
            - name: DD_DOGSTATSD_NON_LOCAL_TRAFFIC
              value: 'true'
            - name: DD_RUNTIME_METRICS_ENABLED
              value: "true"
            - name: DD_JMXFETCH_ENABLED
              value: "true"
          {{- end }}
{{ if .Values.healthChecks.enabled }}
{{ (unset .Values.healthChecks "enabled") | toYaml | indent 10 }}
{{ end }}
          resources:
{{ toYaml .Values.resources | indent 12 }}
          securityContext:
{{ toYaml .Values.securityContext | indent 12 }}
          volumeMounts:
{{ toYaml .Values.volumeMounts | indent 12 }}
            {{- if .Values.certManager.enabled }}
            - mountPath: {{ .Values.certManager.volumeMount.certificates.path }}
              name: {{ template "bola-detection-engine.name" . }}-certificate-secret
              readOnly: true
            {{- end }}
            {{- if .Values.vaultPKIKafkaSecret.enabled }}
            - mountPath: {{ .Values.vaultPKIKafkaSecret.mountpath }}
              name: {{ template "bola-detection-engine.name" . }}-certificate-secret
              readOnly: true
            {{- end }}
            {{- if .Values.vaultPKIKafkaPCISecret.enabled }}
            - mountPath: {{ .Values.vaultPKIKafkaPCISecret.mountpath }}
              name: {{ template "bola-detection-engine.name" . }}-pci-certificate-secret
              readOnly: true
            {{- end }}

    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
      volumes:
{{ toYaml .Values.volumes | indent 8 }}
        {{- if .Values.certManager.enabled }}
        - name: {{ template "bola-detection-engine.name" . }}-certificate-secret
          secret:
            secretName: {{ template "bola-detection-engine.name" . }}-certificate-secret
        {{- end }}
        {{- if .Values.vaultPKIKafkaSecret.enabled  }}
        - name: bola-detection-engine-certificate-secret
          secret:
            secretName: bola-detection-engine-certificate-secret
        {{- end }}
        {{- if .Values.vaultPKIKafkaPCISecret.enabled }}
        - name: {{ template "bola-detection-engine.name" . }}-pci-certificate-secret
          secret:
            secretName: {{ template "bola-detection-engine.name" . }}-pci-certificate-secret
        {{- end }}

