{{/* Reference: https://developer.hashicorp.com/vault/docs/platform/k8s/vso/api-reference#vaultpkisecret */}}
{{- if .Values.vaultPKIKafkaSecret.enabled }}
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultPKISecret
metadata:
  labels:
    app: {{ template "bola-detection-engine.name" . }}
    chart: {{ template "bola-detection-engine.chart" . }}
    release: {{ .Release.Name }}
  name: {{ template "bola-detection-engine.name" . }}-certificate
spec:
  vaultAuthRef: {{ .Values.vaultPKIKafkaSecret.vaultAuthRef }}
  mount: {{ .Values.vaultPKIKafkaSecret.mount }}
  role: {{ .Values.vaultPKIKafkaSecret.role }}
  revoke: {{ .Values.vaultPKIKafkaSecret.revoke }}
  clear: true
  expiryOffset: {{ .Values.vaultPKIKafkaSecret.expiryOffset }}
  commonName: {{ .Values.vaultPKIKafkaSecret.commonName }}
  ttl: {{ .Values.vaultPKIKafkaSecret.ttl }}
  format: {{ .Values.vaultPKIKafkaSecret.format }}
  privateKeyFormat: {{ .Values.vaultPKIKafkaSecret.privateKeyFormat }}
  destination:
    name: {{ template "bola-detection-engine.name" . }}-certificate-secret
    create: true
    type: kubernetes.io/tls
  rolloutRestartTargets:
  - kind: Deployment
    name: api-security-engine-bola-detection-engine
{{- end }}

---

{{- if .Values.vaultPKIKafkaPCISecret.enabled }}
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultPKISecret
metadata:
  labels:
    app: {{ template "bola-detection-engine.name" . }}
    chart: {{ template "bola-detection-engine.chart" . }}
    release: {{ .Release.Name }}
  name: {{ template "bola-detection-engine.name" . }}-pci-certificate
spec:
  vaultAuthRef: {{ .Values.vaultPKIKafkaPCISecret.vaultAuthRef }}
  mount: {{ .Values.vaultPKIKafkaPCISecret.mount }}
  role: {{ .Values.vaultPKIKafkaPCISecret.role }}
  revoke: {{ .Values.vaultPKIKafkaPCISecret.revoke }}
  clear: true
  expiryOffset: {{ .Values.vaultPKIKafkaPCISecret.expiryOffset }}
  commonName: {{ .Values.vaultPKIKafkaPCISecret.commonName }}
  ttl: {{ .Values.vaultPKIKafkaPCISecret.ttl }}
  format: {{ .Values.vaultPKIKafkaPCISecret.format }}
  privateKeyFormat: {{ .Values.vaultPKIKafkaPCISecret.privateKeyFormat }}
  destination:
    name: {{ template "bola-detection-engine.name" . }}-pci-certificate-secret
    create: true
    type: kubernetes.io/tls
  rolloutRestartTargets:
  - kind: Deployment
    name: api-security-engine-bola-detection-engine
{{- end }}
