{{- if .Values.certManager.enabled }}
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: {{ template "bola-detection-engine.name" . }}-vault-issuer
spec:
  vault:
    server: {{ .Values.certManager.vault.server }}
    path: {{ .Values.certManager.vault.path }}
    namespace: {{ .Values.certManager.vault.namespace }}
    auth:
      appRole:
        path: {{ .Values.certManager.vault.appRole.path }}
        roleId: {{ .Values.certManager.vault.appRole.roleId }}
        secretRef:
          name: {{ template "bola-detection-engine.name" $ }}-vault-approle
          key: secretId
{{- end }}
---
{{- if .Values.certManagerPCI.enabled }}
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: {{ template "bola-detection-engine.name" . }}-pci-vault-issuer
spec:
  vault:
    server: {{ .Values.certManagerPCI.vault.server }}
    path: {{ .Values.certManagerPCI.vault.path }}
    namespace: {{ .Values.certManagerPCI.vault.namespace }}
    auth:
      appRole:
        path: {{ .Values.certManagerPCI.vault.appRole.path }}
        roleId: {{ .Values.certManagerPCI.vault.appRole.roleId }}
        secretRef:
          name: {{ template "bola-detection-engine.name" $ }}-pci-vault-approle
          key: secretId
{{- end }}
