{{- if and (include "ingress-controller-ops.createAutoPatchResources" .) (include "ingressController.namespaceExists" .) }}
apiVersion: batch/v1
kind: Job
metadata:
  name: ingress-controller-ops
  namespace: {{ include "ingressController.namespace" . }}
  annotations:
    "helm.sh/hook": "post-install,post-upgrade"
    "helm.sh/hook-weight": "3"
    "helm.sh/hook-delete-policy": "before-hook-creation,hook-succeeded"
spec:
  activeDeadlineSeconds: 150
  template:
{{- include "ingress-controller-ops-hook.install.podTemplate" . | nindent 4 }}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: ingress-controller-ops-cleanup
  namespace: {{ include "ingressController.namespace" . }}
  annotations:
    "helm.sh/hook": "pre-delete"
    "helm.sh/hook-weight": "3"
    "helm.sh/hook-delete-policy": "before-hook-creation,hook-succeeded"
spec:
  activeDeadlineSeconds: 150
  template:
{{- include "ingress-controller-ops-hook.cleanup.podTemplate" . | nindent 4 }}
{{- end }}