{{- if (empty .Values.global.tls.existingSecret) -}}

{{- $dataSenderCertificates := (include "data-sender.gen-certs" .) }}

apiVersion: v1
kind: Secret
type: kubernetes.io/tls
metadata:
  name: {{ template "data-sender.name" . }}-certs-{{.Release.Namespace}}
  labels:
    app: {{ template "data-sender.name" . }}
    chart: {{ template "data-sender.name" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  annotations:
    "helm.sh/hook": "pre-install"
    "helm.sh/hook-delete-policy": "before-hook-creation"
data:
{{ $dataSenderCertificates | indent 2 }}
---
{{if .Values.storeData.onAwsS3}}
apiVersion: v1
kind: Secret
metadata:
  name: aws-auth
type: Opaque
data:
  S3_BUCKET_NAME: {{ .Values.storeData.awsCredentials.s3BucketName | toString | b64enc }}
  S3_BUCKET_ID: {{ .Values.storeData.awsCredentials.s3BucketId | toString | b64enc }}
  S3_BUCKET_SECRET: {{ .Values.storeData.awsCredentials.s3BucketSecret | toString | b64enc }}
  S3_BUCKET_REGION: {{ .Values.storeData.awsCredentials.s3BucketRegion | toString | b64enc }}
{{end}}
{{- end -}}