{{- if eq "gcplb" .Values.global.ingressType }}
{{- if .Values.autoscaling.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "gcplb.fullname" . }}-proxy-hpa
  labels:
    {{- include "gcplb.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "gcplb.fullname" . }}-proxy
  minReplicas: {{ .Values.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.autoscaling.maxReplicas }}
  behavior:
    scaleDown:
    {{- toYaml .Values.autoscaling.behavior.scaleDown | nindent 6 }}
    scaleUp:
    {{- toYaml .Values.autoscaling.behavior.scaleUp | nindent 6 }}
  metrics:
    {{- if .Values.autoscaling.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.autoscaling.targetCPUUtilizationPercentage }}
    {{- end }}
{{- end }}
{{- end }}