standalone: "true"

image:
  registry: imperva.jfrog.io/apisec-airgap-stage
  repository: cloud-connecter
  tag: 0.0.1-master.51-4e238d
  pullPolicy: IfNotPresent

imagePullSecrets:
  - name: apisecurity-credentials

env:
  DEPLOYMENT_PROFILE: "ON-PREM"
  CLOUD_URL: http://onprem-receiver/
  REDIS_SERVER_ADDR: '{"host":"apisec-controller-message-bus", "port":6379, "cred_source": "env", "is_tls_enabled": false}'
  REDIS_HEALTH_CONNECTION: '{"host":"apisec-controller-message-bus", "port":6379, "cred_source": "env", "is_tls_enabled": false}'

initContainerEnv:
  REDIS_PROPS: '[{"host":"apisec-controller-message-bus", "port":6379, "cred_source": "env", "is_tls_enabled":false}]'

volumes:
  - name: tmp
    emptyDir: {}

volumeMounts:
  - mountPath: /tmp
    name: tmp

resources:
  requests:
    memory: "512Mi"
    cpu: "500m"
  limits:
    memory: "1024Mi"
    cpu: "1000m"
