{{- if not ( lookup "v1" "ConfigMap" .Release.Namespace "remote-jwk-url" ) }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: remote-jwk-url
  namespace: {{ .Release.Namespace }}
  annotations:
    meta.helm.sh/release-name: "{{ .Release.name }}"
    meta.helm.sh/release-namespace: "{{ .Release.namespace }}"
  labels:
    app.kubernetes.io/managed-by: Helm
data:
  remote_jwk_url: |
    {{ .Values.env.remote_jwk_url }}
{{- end }}
