standalone: "true"

image:
  registry: imperva.jfrog.io/apisec-airgap-stage
  repository: bola-detection-engine
  tag: 0.0.1-main.109-0b512c
  pullPolicy: IfNotPresent

imagePullSecrets:
  - name: apisecurity-credentials

env:
  LOG_LEVEL: "INFO"
  DEPLOYMENT_PROFILE: "ON-PREM"
  BOLA_SUMMARY_PERIOD: 3600
  REDIS_SERVER_ADDR: '{"host":"apisec-controller-message-bus", "port":6379, "cred_source": "env", "is_tls_enabled": false}'
  REDIS_SERVER_CACHE_ADDR: '{"host":"apisec-controller-message-bus", "port":6379, "cred_source": "env", "is_tls_enabled": false}'
  REDIS_HEALTH_CONNECTION: '{"host":"apisec-controller-message-bus", "port":6379, "cred_source": "env", "is_tls_enabled": false}'
  REDIS_BOLA_BROKERS: '{"host":"apisec-controller-message-bus", "port":6379, "cred_source": "env", "is_tls_enabled": false}'
  EXPIRE_TIME: 28800
  PROMETHEUS_MULTIPROC_DIR: "/tmp/MULTIPROC_DIR_REPORTS"

initContainerEnv:
  REDIS_PROPS: '[{"host":"apisec-controller-message-bus", "port":6379, "cred_source": "env", "is_tls_enabled":false}]'

securityContext:
  readOnlyRootFilesystem: false

volumes:
  - name: tmp
    emptyDir: {}

volumeMounts:
  - mountPath: /tmp
    name: tmp

certManager:
  enabled: false

certManagerPCI:
  enabled: false

equinix: false
