{{- if eq "gcplb" .Values.global.ingressType }}
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: envoy
  namespace: {{ .Release.Namespace }}
spec:
  parentRefs:
  - group: gateway.networking.k8s.io
    kind: Gateway
    name: {{ include "gcplb.fullname" . }}-gateway
  rules:
  - backendRefs:
    - kind: Service
      name: {{ include "gcplb.fullname" . }}-proxy
      port: {{ .Values.service.port }}
    matches:
    - path:
        type: PathPrefix
        value: /
{{- end }}