apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{.Chart.Name}}-role
  namespace: {{ .Release.Namespace }}
rules:
  - apiGroups:
      - "*"
    resources:
      - services
      - pods
    verbs:
      - get
      - list
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{.Chart.Name}}-role-binding
subjects:
  - kind: ServiceAccount
    name: {{ include "cloud-mediator.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: {{.Chart.Name}}-role
  apiGroup: rbac.authorization.k8s.io
