apiVersion: v1
kind: Service
metadata:
  name: {{ include "cloud-mediator.fullname" . }}
  labels:
    {{- include "cloud-mediator.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: https
      protocol: TCP
      name: https
    - port: 8445
      protocol: TCP
      name: health
  selector:
    {{- include "cloud-mediator.selectorLabels" . | nindent 4 }}
