standalone: "true"

image:
  registry: imperva.jfrog.io/apisec-airgap-stage
  repository: summarization-engine
  tag: 0.0.1-master.338-7c2730
  pullPolicy: IfNotPresent

imagePullSecrets:
  - name: apisecurity-credentials

env:
  DEPLOYMENT_PROFILE: "ON-PREM"
  DATA_PUBLISHER: REDIS
  REDIS_SERVER_ADDR: '{"host":"apisec-controller-message-bus", "port":6379, "cred_source": "env", "is_tls_enabled": false}'
  REDIS_CACHE_ADDR: '{"host":"apisec-controller-message-bus", "port":6379, "cred_source": "env", "is_tls_enabled": false}'
  REDIS_HEALTH_CONNECTION: '{"host":"apisec-controller-message-bus", "port":6379, "cred_source": "env", "is_tls_enabled": false}'
  DISCOVERY_AGGREGATE_TIME: 60
  APPL_AGGREGATE_TIME: 120
  AUTH_AGGREGATE_TIME: 120
  PRIORITY_APPL_AGGREGATE_TIME: 60
  PRIORITY_AUTH_AGGREGATE_TIME: 120
  PRIORITY_DISCOVERY_AGGREGATE_TIME: 120
  PRIORITY_EVENT_ACCOUNT_IDS: ""

initContainerEnv:
  REDIS_PROPS: '[{"host":"apisec-controller-message-bus", "port":6379, "cred_source": "env", "is_tls_enabled":false}]'

volumes:
  - name: tmp
    emptyDir: {}

volumeMounts:
  - mountPath: /tmp
    name: tmp

certManager:
  enabled: false

healthChecks:
  enabled: false

resources:
  requests:
    memory: "512Mi"
    cpu: "500m"
  limits:
    memory: "1024Mi"
    cpu: "1000m"
