standalone: "true"

streams:
  - general

image:
  registry: imperva.jfrog.io/apisec-airgap-stage
  repository: normalizer
  tag: 0.0.1-master.602-05cf97
  pullPolicy: IfNotPresent

imagePullSecrets:
  - name: apisecurity-credentials

env:
  DEPLOYMENT_PROFILE: "ON-PREM"
  REDIS_PUBLISHER_CONNECTION: '{"host":"apisec-controller-message-bus", "port":6379, "cred_source": "env", "is_tls_enabled":false}'
  REDIS_CONSUMER_CONNECTION: '{"host":"apisec-controller-message-bus", "port":6379, "cred_source": "env", "is_tls_enabled":false}'
  REDIS_HEALTH_CONNECTION: '{"host":"apisec-controller-message-bus", "port":6379, "cred_source": "env", "is_tls_enabled":false}'
  PUBLISH_EVENTS_WITH_REQUEST_API_DESIGN_ISSUES: true
  PUBLISH_EVENTS_WITH_RESPONSE_API_DESIGN_ISSUES: true

  CONFIG_PUBLISHER_HOST: 'http://api-security-engine-cloud-connecter'
  CONFIG_POLL_FREQUENCY_MINS: 5
  NUM_CFG_DOWNLOADER: 10
  METRICS_SERVER_PORT: 8112

initContainerEnv:
  REDIS_PROPS: '[{"host":"apisec-controller-message-bus", "port":6379, "cred_source": "env", "is_tls_enabled":false}]'

volumes:
  - name: tmp
    emptyDir: {}

volumeMounts:
  - mountPath: /tmp
    name: tmp

resources:
  requests:
    memory: "512Mi"
    cpu: "500m"
  limits:
    memory: "1024Mi"
    cpu: "1000m"
