{{- if and (eq "kong" .Values.global.ingressType) (include "ingress-controller-ops.createAutoPatchResources" .) }}
apiVersion: configuration.konghq.com/v1
kind: KongClusterPlugin
metadata:
  name: {{ .Values.pluginName }}
  annotations:
    "kubernetes.io/ingress.class": {{ .Values.ingressClass }}
    "helm.sh/hook": "post-install,post-upgrade"
    "helm.sh/hook-delete-policy": "before-hook-creation,hook-failed"
    "helm.sh/hook-weight": "5"
config:
  pass_on_failure: {{ .Values.global.failOpen }}
  grpc:
    url: localhost
    port: 10000
    is_ssl: false
    timeout: 30000
    # verify_server_certificate: false
    # root_ca_path: "/var/work/ca"
  limits:
    max_buffer_size: 4194304
    max_grpc_recv_size: 4194304
  initial_send_modes:
    request_headers: DEFAULT
    request_body: STREAMED
    response_headers: DEFAULT
    response_body: STREAMED
plugin: impv-waf-plugin
{{- end }}