{{- if and (eq "kong" .Values.global.ingressType) (include "ingress-controller-ops.createAutoPatchResources" .) -}}
kind: ConfigMap
metadata:
  name: kong-gateway-patch
  namespace: {{ include "ingressController.namespace" . }}
  annotations:
    "helm.sh/hook": post-install, post-upgrade
    "helm.sh/hook-delete-policy": hook-succeeded, hook-failed, before-hook-creation
    "helm.sh/hook-weight": "-5"  
apiVersion: v1
data:
  patch.json: |
{{ include "kong.pluginInjection" . | indent 4 }}
---
kind: ConfigMap
metadata:
  name: kong-gateway-counter-patch
  namespace: {{ include "ingressController.namespace" . }}
  annotations:
    "helm.sh/hook": pre-delete
    "helm.sh/hook-delete-policy": before-hook-creation, hook-succeeded, hook-failed
    "helm.sh/hook-weight": "-5" # Must be created before the cleanup job  
apiVersion: v1
data:
  patch.json: |
{{ include "kong.counterPatch" . | indent 4 }}
{{- end -}}